#!/bin/bash

domain="example.com"

declare -A hosts=(
    [n0a]=00:<redacted>
    [n0b]=00:<redacted>
    [n0c]=00:<redacted>
    [n0d]=00:<redacted>
)

declare -A IPs=(
    [n0a]=192.168.<redacted>
    [n0b]=192.168.<redacted>
    [n0c]=192.168.<redacted>
    [n0d]=192.168.<redacted>
)